//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonDetail
    {
        public int ID { get; set; }
        public Nullable<int> TeacherLessonId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TeachersLesson TeachersLesson { get; set; }
    }
}
